### ISSUE TITLE
高精度模板(基于双模数NTT) | DarkSharpness's Blog

### ISSUE THREAD

**Issue by DarkSharpness** [DarkSharpness/darksharpness.github.io#13]
https://darksharpness.github.io/2022/11/19/%E9%AB%98%E7%B2%BE%E5%BA%A6%E6%A8%A1%E6%9D%BF(%E5%9F%BA%E4%BA%8E%E5%8F%8C%E6%A8%A1%E6%95%B0NTT)/number/ 

 由于作业要求，我需要写一个压位的高精度的模板，并且需要通过FFT / NTT对于乘法进行优化。 说实话，我是不太喜欢(不会)写这种又暴又难调的的模板的，这对我来说还是非常具有挑战的。 如果你还不会 FFT/NTT，不妨看看 这个(from OIwiki) 本文将侧重于基于双模 NTT 的乘法是如何实现，对于其他的细节也会提到。 基本思路由于我担心FFT压位会爆double精度(事实证明压到 $10

**Comment by zsq259** [comment]
催更牛顿迭代高精度除法qwq

**Comment by DarkSharpness** [comment]
> 催更牛顿迭代高精度除法qwq

有空再说 orz（zsq佬别卖菜
